In [1]:
# Welcome to your new notebook
# Type here in the cell editor to add code!
import pandas as pd

# path to your file in Fabric
file_path = "abfss://136a6b91-7b1c-4a1a-a8c0-9e81cf77e07c@onelake.dfs.fabric.microsoft.com/3ca45b72-dee5-4e97-b74a-d90763b17d54/Files/Sample - Superstore.csv"

df = pd.read_csv(file_path, encoding="latin1")

df.head()

StatementMeta(, 5886a936-50e0-42ff-8010-2ca62d172969, 3, Finished, Available, Finished, False)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [2]:
# Remove nulls
df = df.dropna()

df.head()

# Convert date
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])
# Create new column
df['Year'] = df['Order Date'].dt.year

# Profit margin
df['Profit Margin'] = df['Profit'] / df['Sales']
df['Profit Margin'] = df['Profit Margin'].round(2)

# Sales category - segmentation
df['Sales Category'] = pd.cut(
df['Sales'],
bins=[0, 100, 500, 1000, 10000],
labels=['Low', 'Medium', 'High', 'Very High']
)

df.head()

StatementMeta(, 5886a936-50e0-42ff-8010-2ca62d172969, 4, Finished, Available, Finished, False)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year,Profit Margin,Sales Category
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,0.16,Medium
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,0.30,High
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,0.47,Low
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,-0.40,High
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,0.11,Low

In [3]:
# Clean column names (VERY IMPORTANT)
df.columns = df.columns.str.replace(" ", "_")

df.head()

StatementMeta(, 5886a936-50e0-42ff-8010-2ca62d172969, 5, Finished, Available, Finished, False)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit,Year,Profit_Margin,Sales_Category
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,0.16,Medium
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,0.30,High
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,0.47,Low
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,-0.40,High
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,0.11,Low

In [4]:
# df.to_parquet("/lakehouse/default/Tables/clean_sales")

df_spark = spark.createDataFrame(df)

df_spark.write.mode("overwrite").saveAsTable("clean_sales")

StatementMeta(, 5886a936-50e0-42ff-8010-2ca62d172969, 6, Finished, Available, Finished, False)

In [5]:
spark.sql("SHOW TABLES").show()

StatementMeta(, 5886a936-50e0-42ff-8010-2ca62d172969, 7, Finished, Available, Finished, False)

+--------------------+------------+-----------+
|           namespace|   tableName|isTemporary|
+--------------------+------------+-----------+
|`sales-fabric-pro...| clean_sales|      false|
|`sales-fabric-pro...|dim_customer|      false|
|`sales-fabric-pro...|    dim_date|      false|
|`sales-fabric-pro...| dim_product|      false|
|`sales-fabric-pro...|  fact_sales|      false|
+--------------------+------------+-----------+

Create dimension tables:

In [6]:
dim_customer = df[['Customer_ID', 'Customer_Name']].drop_duplicates()
dim_product = df[['Product_ID', 'Product_Name', 'Category']].drop_duplicates()
dim_date = df[['Order_Date', 'Year']].drop_duplicates()

fact_sales = df[['Sales', 'Quantity', 'Customer_ID', 'Product_ID', 'Order_Date']]

StatementMeta(, 5886a936-50e0-42ff-8010-2ca62d172969, 8, Finished, Available, Finished, False)

In [7]:
dim_customer.to_parquet("/lakehouse/default/Tables/dim_customer")
dim_product.to_parquet("/lakehouse/default/Tables/dim_product")
dim_date.to_parquet("/lakehouse/default/Tables/dim_date")
fact_sales.to_parquet("/lakehouse/default/Tables/fact_sales")

StatementMeta(, 5886a936-50e0-42ff-8010-2ca62d172969, 9, Finished, Available, Finished, False)

In [8]:
# Clean column names first
dim_customer.columns = dim_customer.columns.str.replace(" ", "_")
dim_product.columns = dim_product.columns.str.replace(" ", "_")
dim_date.columns = dim_date.columns.str.replace(" ", "_")
fact_sales.columns = fact_sales.columns.str.replace(" ", "_")

# Convert pandas -> spark
dim_customer_spark = spark.createDataFrame(dim_customer)
dim_product_spark = spark.createDataFrame(dim_product)
dim_date_spark = spark.createDataFrame(dim_date)
fact_sales_spark = spark.createDataFrame(fact_sales)

# Save as REAL tables
dim_customer_spark.write.mode("overwrite").saveAsTable("dim_customer")
dim_product_spark.write.mode("overwrite").saveAsTable("dim_product")
dim_date_spark.write.mode("overwrite").saveAsTable("dim_date")
fact_sales_spark.write.mode("overwrite").saveAsTable("fact_sales")

StatementMeta(, 5886a936-50e0-42ff-8010-2ca62d172969, 10, Finished, Available, Finished, False)

CREATE DIM_PRODUCT WITH SURROGATE KEY (duplicated prod id OFF-PA-10000477 with different prod names)

In [9]:
# Create dimension table
dim_product = df[
    ['Product_ID', 'Product_Name', 'Category']
].drop_duplicates().reset_index(drop=True)

# Create surrogate key
dim_product['Product_Key'] = dim_product.index + 1

# Reorder columns
dim_product = dim_product[
    ['Product_Key', 'Product_ID', 'Product_Name', 'Category']
]

dim_product.head()

StatementMeta(, 5886a936-50e0-42ff-8010-2ca62d172969, 11, Finished, Available, Finished, False)

,Product_Key,Product_ID,Product_Name,Category
0,1,FUR-BO-10001798,Bush Somerset Collection Bookcase,Furniture
1,2,FUR-CH-10000454,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Furniture
2,3,OFF-LA-10000240,Self-Adhesive Address Labels for Typewriters b...,Office Supplies
3,4,FUR-TA-10000577,Bretford CR4500 Series Slim Rectangular Table,Furniture
4,5,OFF-ST-10000760,Eldon Fold 'N Roll Cart System,Office Supplies

Merge tables -ADD PRODUCT_KEY TO FACT TABLE

In [11]:
fact_sales = df.merge(
    dim_product,
    on=['Product_ID'],
    how='left'
)

fact_sales.head()

StatementMeta(, 5886a936-50e0-42ff-8010-2ca62d172969, 23, Finished, Available, Finished, False)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Sales,Quantity,Discount,Profit,Year,Profit_Margin,Sales_Category,Product_Key,Product_Name_y,Category_y
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,2016,0.16,Medium,1,Bush Somerset Collection Bookcase,Furniture
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,2016,0.30,High,2,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Furniture
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,2016,0.47,Low,3,Self-Adhesive Address Labels for Typewriters b...,Office Supplies
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,2015,-0.40,High,4,Bretford CR4500 Series Slim Rectangular Table,Furniture
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,2015,0.11,Low,5,Eldon Fold 'N Roll Cart System,Office Supplies

In [12]:
# Create dim_product
dim_product = df[
    ['Product_ID', 'Product_Name', 'Category']
].drop_duplicates().reset_index(drop=True)

# Add surrogate key
dim_product['Product_Key'] = dim_product.index + 1

# Merge surrogate key into fact table
fact_sales = df.merge(
    dim_product[['Product_Key', 'Product_ID', 'Product_Name']],
    on=['Product_ID', 'Product_Name'],
    how='left'
)

fact_sales.head()

StatementMeta(, 5886a936-50e0-42ff-8010-2ca62d172969, 26, Finished, Available, Finished, False)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit,Year,Profit_Margin,Sales_Category,Product_Key
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,0.16,Medium,1
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,0.30,High,2
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,0.47,Low,3
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,-0.40,High,4
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,0.11,Low,5

STEP 3 — KEEP ONLY NEEDED FACT COLUMNS

In [13]:
fact_sales = fact_sales[
    ['Sales', 'Quantity', 'Customer_ID', 'Order_Date', 'Product_Key']
]

StatementMeta(, 5886a936-50e0-42ff-8010-2ca62d172969, 28, Finished, Available, Finished, False)

STEP 4 — SAVE TABLES

In [16]:
dim_product_spark.write \
    .mode("overwrite") \
    .option("overwriteSchema", "true") \
    .saveAsTable("dim_product")

StatementMeta(, 5886a936-50e0-42ff-8010-2ca62d172969, 31, Finished, Available, Finished, False)

In [17]:
fact_sales_spark.write \
    .mode("overwrite") \
    .option("overwriteSchema", "true") \
    .saveAsTable("fact_sales")

StatementMeta(, 5886a936-50e0-42ff-8010-2ca62d172969, 32, Finished, Available, Finished, False)

In [15]:
# Spark conversion
dim_product_spark = spark.createDataFrame(dim_product)
fact_sales_spark = spark.createDataFrame(fact_sales)

# Save tables
dim_product_spark.write.mode("overwrite").saveAsTable("dim_product")
fact_sales_spark.write.mode("overwrite").saveAsTable("fact_sales")

StatementMeta(, 5886a936-50e0-42ff-8010-2ca62d172969, 30, Finished, Available, Finished, False)

AnalysisException: [_LEGACY_ERROR_TEMP_DELTA_0007] A schema mismatch detected when writing to the Delta table (Table ID: de1c0f12-236e-408d-befd-c099c2738707).
To enable schema migration using DataFrameWriter or DataStreamWriter, please set:
'.option("mergeSchema", "true")'.
For other operations, set the session configuration
spark.databricks.delta.schema.autoMerge.enabled to "true". See the documentation
specific to the operation for details.

Table schema:
root
-- Product_ID: string (nullable = true)
-- Product_Name: string (nullable = true)
-- Category: string (nullable = true)


Data schema:
root
-- Product_ID: string (nullable = true)
-- Product_Name: string (nullable = true)
-- Category: string (nullable = true)
-- Product_Key: long (nullable = true)


To overwrite your schema or change partitioning, please set:
'.option("overwriteSchema", "true")'.

Note that the schema can't be overwritten when using
'replaceWhere'.